global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: boriowomoses2@gmail.com
  

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: email-alerts


inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname']
    

receivers:
- name: 'email-alerts'
  email_configs:
    - to: 'temiadebayo@gmail.com'
      send_resolved: true

