apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
    containers:
      image: /mosesboriowo/gads_app:2
      ports:
      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: fask
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
