global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
- /etc/prometheus/alert.rules

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
- job_name: 'python-app'
  static_configs:
    - targets: ['python-app:8000']









